import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DataContextProvider } from "@/contexts/DataContextProvider";
import { ReactFlowProvider } from "@xyflow/react";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full overflow-hidden">
        <ReactFlowProvider>
          <DataContextProvider>
            {" "}
            <div className="flex h-full flex-col">
              <NavBar />
              {children}
            </div>
          </DataContextProvider>
        </ReactFlowProvider>
      </body>
    </html>
  );
}
